// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Mutation struct {
}

type NovaCategoria struct {
	Descricao string `json:"descricao"`
}

type NovaFormaPagamento struct {
	Descricao string `json:"descricao"`
}

type NovoLancamento struct {
	Descricao        string  `json:"descricao"`
	Valor            float64 `json:"valor"`
	Observacao       *string `json:"observacao,omitempty"`
	Recorrencia      *int32  `json:"recorrencia,omitempty"`
	TipoID           string  `json:"tipoId"`
	CategoriaID      string  `json:"categoriaId"`
	FormaPagamentoID string  `json:"formaPagamentoId"`
	NecessidadeID    string  `json:"necessidadeId"`
}

type NovoNivelNecessidade struct {
	Descricao string `json:"descricao"`
	Cor       string `json:"cor"`
}

type NovoTipoLancamento struct {
	Descricao string `json:"descricao"`
}

type Query struct {
}
